#!/bin/bash
command_to_run="$*"
if [ -z "$command_to_run" ]; then
	echo "Usage: sudo command"
	echo "Runs command with administrator privileges."
	exit
fi

# Convert to Windows path
sudo_dir="$(realpath $(dirname $0))"
backend="$(echo $sudo_dir/sudobackend.sh | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')"

fifoid="$sudo_dir/.sudo.$RANDOM"
mkfifo "$fifoid.finish"
mkfifo "$fifoid.pidf"
mkfifo "$fifoid.sigint"

echo "$command_to_run" >"$fifoid.command"
echo "/proc/$$/fd" >"$fifoid.fd"

# Create fifo for stdout
if [ -t 1 ]; then
	# Terminal
	echo "/proc/$$/fd/1" >"$fifoid.stdout"
else
	# Not terminal
	mkfifo "$fifoid.opipe"
	echo "$fifoid.opipe" >"$fifoid.stdout"
fi

# Create fifo for stderr
if [ -t 2 ]; then
	# Terminal
	echo "/proc/$$/fd/2" >"$fifoid.stderr"
else
	# Not terminal
	mkfifo "$fifoid.epipe"
	echo "$fifoid.epipe" >"$fifoid.stderr"
fi

# Get bash path
pushd / >/dev/null 2>&1
bash_path="$(pwd -W)bin/sh"
popd >/dev/null 2>&1

# Run command
powershell.exe Start-Process \"$bash_path\" \"$backend\", \"$fifoid\", \"$(pwd)\" -Verb RunAs -WindowStyle Hidden 2>/dev/null
if [ $? -ne 0 ]; then
	echo "UAC elevation was canceled" >&2
	exit 1
fi

# Get pid
pid=$(cat "$fifoid.pidf")
rm "$fifoid.pidf"

trap "rm \"$fifoid.finish\"; rm \"$fifoid.sigint\"" EXIT

# Wait
trap "echo 1 >\"$fifoid.sigint\" && sleep 0.1" SIGINT

# Cat stdout fifo
if [ ! -t 1 ]; then
	cat "$fifoid.opipe" &
fi

# Cat stderr fifo
if [ ! -t 2 ]; then
	cat "$fifoid.epipe" >&2 &
fi

while true; do
	res=$(cat "$fifoid.finish")
	if [ ! -z "$res" ]; then
		break
	fi
done