#!/bin/bash
if [ -f /etc/profile ]; then
	. /etc/profile
elif [ -f ~/.bash_profile ]; then
	. ~/.bash_profile
elif [ -f ~/.bash_login ]; then
	. ~/.bash_login
elif [ -f ~/.profile ]; then
	. ~/.profile
fi

if [ -f ~/.sudorc ]; then
	. ~/.sudorc
fi