#!/bin/bash
command_to_run="$*"
if [ -z "$command_to_run" ]; then
	echo "Usage: sudo command"
	echo "Runs command with administrator privileges."
	exit
fi

# Convert to Windows path
sudo_dir="$(realpath $(dirname $0))"
backend="$(echo $sudo_dir/sudobackend.sh | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')"

fifoid="$sudo_dir/.sudo.$RANDOM"
mkfifo "$fifoid.finish"
mkfifo "$fifoid.pidf"
mkfifo "$fifoid.sigint"

echo "$command_to_run">"$fifoid.command"
echo "/proc/$$/fd">"$fifoid.fd"

# Get bash path
pushd / >/dev/null 2>&1
bash_path="$(pwd -W)bin/sh"
popd >/dev/null 2>&1

# Run command
powershell.exe Start-Process \"$bash_path\" \"$backend\", \"$fifoid\", \"$(pwd)\" -Verb RunAs -WindowStyle Hidden 2>/dev/null
if [ $? -ne 0 ]; then
	echo "UAC elevation was canceled" >&2
	exit 1
fi

# Get pid
pid=$(cat "$fifoid.pidf")
rm "$fifoid.pidf"

trap "rm \"$fifoid.finish\"; rm \"$fifoid.sigint\"" EXIT

# Wait
trap "echo 1 >\"$fifoid.sigint\" && sleep 0.1" SIGINT

while true; do
	res=$(cat "$fifoid.finish")
	if [ ! -z "$res" ]; then
		break
	fi
done