#!/bin/bash

# http://stackoverflow.com/a/21295806/1641422
fsutil dirty query $SYSTEMDRIVE >/dev/null 2>&1
ret=$?
if [ $ret -eq 127 ]; then
	# http://stackoverflow.com/a/28268802
	fltmc >/dev/null 2>&1
	ret=$?
fi
if [ $ret -eq 0 ]; then
	exec $*
fi

command_to_run="$*"
if [ -z "$command_to_run" ]; then
	echo $'Usage: sudo command\nRuns command with administrator privileges.'; exit
fi

if [ "$MSYSTEM" == "" ]; then
	echo $'sudo does not support current terminal\nPlease try again in git bash' >&2; exit 1
fi

# Convert to Windows path
sudo_dir="$(realpath $(dirname $0))"
backend="$sudo_dir/sudobackend"

fifoid="/tmp/.sudo.$RANDOM"
mkfifo "$fifoid.finish"
mkfifo "$fifoid.pidf"
mkfifo "$fifoid.sigint"

echo "$command_to_run" >"$fifoid.command"

# Create fifos
for fd in 0 1 2; do
	if [ -t $fd ]; then
		# Terminal
		echo "/proc/$$/fd/$fd" >"$fifoid.fd$fd"
	else
		# Not terminal
		mkfifo "$fifoid.pipe$fd"
		echo "$fifoid.pipe$fd" >"$fifoid.fd$fd"
	fi
done

function clean {
	rm "$fifoid.finish" "$fifoid.sigint" "$fifoid.pidf" "$fifoid.command"

	# Remove stdin/stdout/stderr
	for fd in 0 1 2; do
		if [ ! -t $fd ]; then
			rm "$fifoid.pipe$fd"
		fi
		rm "$fifoid.fd$fd"
	done
}
trap clean EXIT

# Run command
powershell.exe Start-Process \"$(cygpath -w /bin/)bash\" \"$backend\", \"$fifoid\", \"$(pwd)\" -Verb RunAs -WindowStyle Hidden 2>/dev/null
if [ $? -ne 0 ]; then
	echo "UAC elevation was canceled" >&2
	exit 1
fi

# Get pid
pid=$(cat "$fifoid.pidf")

# Wait
trap "echo 1 >\"$fifoid.sigint\" && sleep 0.1" SIGINT

# Pass stdin fifo
if [ ! -t 0 ]; then
	( cat <&3 >"$fifoid.pipe0" & ) 3<&0
fi

# Cat stdout and stderr
for fd in 1 2; do
	if [ ! -t $fd ]; then
		cat "$fifoid.pipe1" &
	fi
done

while true; do
	res=$(cat "$fifoid.finish")
	if [ ! -z "$res" ]; then
		break
	fi
done
